apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auracut-cert
  namespace: salon
spec:
  secretName: salon-listener-tls
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  dnsNames:
    - www.auracut.store
