apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: salon-http-redirect
  namespace: salon
spec:
  parentRefs:
    - name: salon-gateway
      sectionName: http

  hostnames:
    - "www.auracut.store"

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301