apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: salon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: myacr10.azurecr.io/auth-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: salon-secrets
                  key: NODE_ENV
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: salon-secrets
                  key: JWT_SECRET
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: salon-secrets
                  key: AUTH_DB_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3