apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: salon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: myacr10.azurecr.io/booking-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: salon-secrets
                  key: NODE_ENV
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: salon-secrets
                  key: JWT_SECRET
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: salon-secrets
                  key: BOOKING_DB_URL
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "150Mi"
              cpu: "128m"
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3